server:
  port: 18100
  servlet:
    context-path: /eureka_server

spring:
  application:
    # 服务名
    name: EurekaServer
  security:
    basic:
      # 开启基于HTTP Basic的认证
      enable: true
    user:
      name: zpc
      password: 123456

eureka:
  instance:
    # 注册中心域名
    hostname: localhost
  client:
    # 客户端访问URL
    service-url.defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:18101${server.servlet.context-path}/eureka
    # 是否在注册中心注册
    register-with-eureka: true
    # 是否从注册中心获取服务
    fetch-registry: true
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 扫描失效服务的间隔时间
    eviction-interval-timer-in-ms: 1000
