server:
  port: 18100
  servlet:
    context-path: /eureka_server

spring:
  application:
    # 服务名
    name: EurekaServer

eureka:
  instance:
    # 注册中心域名
    hostname: localhost
  client:
    # 客户端访问URL
    service-url.defaultZone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka
    # 是否在注册中心注册
    register-with-eureka: false
    # 是否从注册中心获取服务
    fetch-registry: false
