server:
  port: 18090
  servlet:
    context-path: /blog

spring:
  application:
    # 服务名称
    name: blog_app

eureka:
  client:
    # 注册中心的地址
    service-url.defaultZone: http://zpc:123456@localhost:18100/eureka_server/eureka
    # 是否在注册中心注册
    register-with-eureka: false
    # 是否从注册中心获取信息
    fetch-registry: true

fallenangel:
  music:
    service: music-service
    music-service: http://${fallenangel.music.service}/music/music/list
